# Generated by Django 6.0 on 2026-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_engine_hours_booking_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('Morning', 'Morning (08:00 AM - 12:00 PM)'), ('Afternoon', 'Afternoon (12:00 PM - 04:00 PM)'), ('Evening', 'Evening (04:00 PM - 08:00 PM)')], default='Morning', max_length=50),
        ),
    ]
