# Generated by Django 6.0 on 2026-07-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(blank=True, default='09:00', max_length=50, null=True),
        ),
    ]
